proxy.hostname=http://127.0.0.1:8080
proxy.npm-path=/packages
proxy.health-path=/api/health
proxy.package-cache-dir=
proxy.monitored-packages=bfarm.terminologien.icd10gm,bfarm.terminologien.ops
proxy.protected-packages=bfarm.terminologien.ops
# Welches Backend verwenden wir?
proxy.backend-mode=basicauth
# Endpunkt-Url der Npm-Registry
#proxy.target-url=https://gitlab.fokus.fraunhofer.de/api/v4/projects/[project_id]/packages/npm
proxy.target-url=https://REGION-npm.pkg.dev/PROJECT/REGISTRY_NAME
# artifact registry settings to retrieve annotations
proxy.google.cloud.annotation.processing.enabled=true
# Credentials (gitlab mode)
proxy.gitlab-token=glpat-
# Credentials (basicauth mode)
proxy.username=REPLACE_ME
proxy.password=REPLACE_ME
# Wie oft soll in der NPM-Registry nach neuen Paketen gesucht werden?
proxy.update-interval-in-ms=60000
# Properties for (dynamic) RSS Feed
proxy.feeds-path=/feeds
proxy.feed-path-hl7=/package-feed.xml
proxy.feed-update-interval-in-ms=60000
# Properties fuer Token Generierung and Validierung
# Endpoint (Token Generierung), Schluesselmaterial + Gueltigkeitsdauer
proxy.token-path=/api/generate-token
proxy.key=REPLACE_ME
proxy.validity-duration-in-days=1000
# Properties fuer Rate Limiting
proxy.rate-limiting.enabled=true
proxy.rate-limiting.limit=100
proxy.rate-limiting.window-duration=300000
# Properties for API Key (to bypass rate limiting)
proxy.rate-limiting.api-key-header=X-API-Key
proxy.rate-limiting.api-key=REPLACE_ME
# enable springdoc-openapi
springdoc.api-docs.enabled=true
# disable swagger-ui
springdoc.swagger-ui.enabled=false
# path to the api-docs
springdoc.api-docs.path=/docs/v3/api-docs
# excluded path(s) - comma separated
springdoc.paths-to-exclude=/api/health,/api/health/liveness
# open api version
springdoc.api-docs.version=openapi_3_0
# disable auto-tagging
springdoc.auto-tag-classes=false
# server-url(s) for generated api-docs - comma separated
proxy.api-docs.server-url=http://localhost:8080,https://terminologien.bfarm.de
# title and version for generated api-docs
proxy.api-docs.title=ZTS - FHIR Package API
proxy.api-docs.version=1.0.0
